---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: argocd
  name: nginx-pv
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /srv/nfs/kubedata/nginx-front-end

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: argocd
  name: nginx-pvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
